### ISSUE TITLE
Script for adding new/existing users to a group to an environment/cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/opfcli#27]
I'm imagining the usage would be something like: 

```bash
$ opfcli user add <env> <cluster> <users_list> <group_name>
```

Other features I think would be useful: 

```bash
# List users in a group for an env/cluster
$ opfcli user list <env> <cluster> <group_name>

# List groups in a cluster, by listing the metadata.name in groups directory for all groups
$ opfcli user list <env> <cluster> groups
```

Feel free to add further suggestion/amendments

**Comment by larsks** [comment]
I'm proposing something like:

```
opfcli user add [--cluster <cluster>] [--env <environment>] [--user-file <path>] <group_name> [<user> [...]]
```

`--cluster` and `--env` are options (rather than positional parameters) so they can be put in the config file (on the assumption that someone will generally be operating on the same cluster).

Users can be added either from a file (`--user-file`), or provided explicitly on the command line. If none of the above, should we open the user file in an editor?

**Comment by HumairAK** [comment]
> (on the assumption that someone will generally be operating on the same cluster)

I think I'm not getting something...how do we decide what the default values are if these are optional?

**Comment by larsks** [comment]
> I think I'm not getting something...how do we decide what the default values are if these are optional?

I think we make them required options (so, either set via the command line, or set via the config file).

**Comment by HumairAK** [comment]
Got it, then yes this sounds good to me!

> should we open the user file in an editor? 

Not sure the added work required for this, but I'd say it's not required, but cool to have.

**Comment by tumido** [comment]
Is this still needed since we don't ksops group resources anymore and all (except cluster-admins) live in `cluster-scope/base` anyways?

**Comment by tumido** [comment]
I think we don't need a cli command to add/remove a line to/from a manifest

**Comment by HumairAK** [comment]
fair enough! closing.
