### ISSUE TITLE
Extracting the ca.crt secret for kafka onboarding from opf-kafka namespace

### ISSUE THREAD

**Issue by HumairAK** [operate-first/opfcli#31]
This requires ocp access to zero cluster, and accessing a secret key value.

The key value is `ca.crt` from secret `odh-message-bus-cluster-ca-cert` found in https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-kafka/secrets/odh-message-bus-cluster-ca-cert.

**Comment by tumido** [comment]
@HumairAK what do you expect from this feature?

do something like `oc get` and then fetch certain key from the data? How much useful is it if it would work only for operate first maintainers who already have access to that namespace.

If the aim is to make the cert public, we can just store it in the git in plain text format and make it public that way.

In that case this command might come useful for keeping the cert in git up to date with the one generated by kafka.

**Comment by tumido** [comment]
FTR:
https://github.com/operate-first/opfcli/pull/37#issuecomment-861392227
https://github.com/operate-first/opfcli/pull/37#issuecomment-861428570

**Comment by HumairAK** [comment]
yeah the usefulness of the command was brought into question in slack as well. 

> If the aim is to make the cert public, we can just store it in the git in plain text format and make it public that way. 

I'm fine with that. I suggested as much in chat. 

> In that case this command might come useful for keeping the cert in git up to date with the one generated by kafka.

In hindsight, I'm not sure we will do this frequently enough to warrant a separate cli feature. But I'm not against bringing in the PR made by @larsks to have a framework for other commands that will interact with k8s api. If it's not useful, we can always remove it :shrug:

**Comment by HumairAK** [comment]
This is a bit stale now, closing -- if someone feels it should be re-opened please do so with reasoning.
