### ISSUE TITLE
[Automation] Is the CLI `cwd` aware?

### ISSUE THREAD

**Issue by tumido** [operate-first/opfcli#32]
I actually think we may include the updates to `argocd-app` as part of this (and thus the automate the full onboarding process), by just requiring the invoker to provide a path to the argocd-apps cloned repo. wdyt?

_Originally posted by @HumairAK in https://github.com/operate-first/SRE/issues/305#issuecomment-840108267_

That depends if we want the cli to be context aware - like having a config file with paths to `apps` and `argocd-apps` and so on. Or do we want the cli to be "stateless" and oblivious to its `cwd`? I think I like the idea of having a shared config file and use the cli from any place in the system, that sounds nice to me. However this highers the entry cost - you need to set up the cli before you can use it. 

I think we can do a wizard on `cli init` or something asking for the paths..

**Comment by larsks** [comment]
I'm happy with the behavior as currently implemented, where the command is repository-aware (it looks for a config in the root of a git repository). I can see an argument for implementing some global defaults in addition to a per-repository configuration, but I'm not sure we need anything fancier than that.

**Comment by tumido** [comment]
I'm happy with the current solution as well :slightly_smiling_face:

**Comment by HumairAK** [comment]
same, closing
