### ISSUE TITLE
Add `opfcli` to the Operate First community 'toolbox'

### ISSUE THREAD

**Issue by quaid** [operate-first/opfcli#43]
**Is your feature request related to a problem? Please describe.**

From what I can tell, it seems we do not have `opfcli` in the community's Toolbox image. This seems like a straightforward oversight we can fix. But perhaps there is backstory here I don't know?

So I'm checking here to see if it's a reasonable feature request. I did consider filing a PR against the Toolbox, but I am not entirely sure that to put in the Dockerfile with the four different architectures in the release:

https://github.com/operate-first/opfcli/releases/tag/v0.2.0

**Describe the solution you'd like**

We recommend (to some degree) the use of the Operate First community Toolbox (https://quay.io/repository/operate-first/opf-toolbox).

When I download and enter that Toolbox, I would like to see the `opfcli` tool available for use.

**Describe alternatives you've considered**

I certainly can install the `opfcli` command manually in my Toolbox, but then so will every other contributor who is using the Toolbox to do `opfcli`-type work.

Frankly, I'm not sure I'll use the `opfcli` tool anytime soon, but this seems to match the philosophy of having a user and contributor focused Toolbox image.

**Comment by HumairAK** [comment]
You are right, it should be part of the toolbox, let's add this for discussion for next sprint planning :) 
good call!

**Comment by HumairAK** [comment]
This is resolved, opfcli is in the toolbox cli now.
