### ISSUE TITLE
Automate adding users to any ocp group

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/opfcli#46]
In response to `operate-first` #support channel. Implement automating of getting access to `grafana-viewer` group and if does not exist in the desired cluster, it add the group to said cluster.

Tasks:
- [x] implement ability to add users to group
- [ ] implement way to run the `opfcli add-users` command based on chat command (tekton w/ github issue, slack, gchat, or other)

**Comment by HumairAK** [comment]
I'd generalize the title to "automate adding users to any ocp group"
