### ISSUE TITLE
Add release automation

### ISSUE THREAD

**Issue by larsks** [operate-first/opfcli#5]
I'd like to automatically generate a new release (with a binary build) when we push a new tag. I would normally just set up a GitHub workflow for this; is that okay, or would we prefer to handle builds via some other mechanism?

**Comment by tumido** [comment]
/cc @harshad16, @goern 

can AI-CoE CI help with this? Do you guys build golang binaries? (Not docker images in this case but rather binaries and attach them to GH releases)

**Comment by goern** [comment]
Yes def! I want some Go tekton build pipeline too! :) 

I think harshad is out of resources right now (correct me if I'm wrong) But we should invest in this task, so @larsks @tumido wanna take it? I'm happy to review

/triage needs-information
/kind feature

**Comment by larsks** [comment]
@goern I'm happy to take it, but I have no idea where to start. Can you point me at docs/examples of what needs to be done?

**Comment by goern** [comment]
seeAlso https://operatefirst.slack.com/archives/C01RT0S2WKX/p1621517096027500

**Comment by tumido** [comment]
Just to summarize the release flow here:

1. Maintainer creates an release issue in GH
2. Bot creates a PR with version bump and changelog update
3. Maintainer reviews and merges the PR
4. Bot creates a git tag and pushes the tag
5. Bot creates a github release
6. Bot builds golang binaries and attaches them to github release

Steps 1.-4. are solved by https://github.com/operate-first/opfcli/pull/7
Steps 5. and 6. are to be solved via https://github.com/thoth-station/thoth-application/issues/1362

Is that correct?

**Comment by goern** [comment]
ja, sounds good
/lgtm

**Comment by tumido** [comment]
@goern do you have any pointers to where to start on defining Tekton pipelines that fits into AICoE-CI for the golang builds?

**Comment by goern** [comment]
ja, at https://github.com/AICoE/aicoe-ci/tree/master/pipeline and `../task/` of that repo

/assign @harshad16

**Comment by tumido** [comment]
@goern said their pretty short on resources now, so we if we really need to get going on this, we should come up with something interim (or try implementing it via AICoE-CI ourselves).

@larsks If we choose to use GH Actions for an interim solution, that's fine - AICoE-CI team will convert it to Tekton pipelines once they have time to spare on this.

**Comment by goern** [comment]
if the binary has been build, we can use https://github.com/thoth-station/thoth-ops-infra/pull/35 to create a Tekton task, that will `gh release  create 2021.05.28 --draft --notes "ah, just a test" --prerelease --title "test release"` and `gh release upload <tag> <files>` , the task would get the tag-release as an input and required a github token as ENV
