### ISSUE TITLE
Option to specify quota and add limit range for create-project

### ISSUE THREAD

**Issue by HumairAK** [operate-first/opfcli#8]
Example:
`opfcli create-project $project $team -d $description -q $quota -nl` 

The default behaviour I think should be to also add a limit range to a new namespace, the `-nl` flag should give us the option to not do this in a scenario we don't want to do this.

Where `-q` is one of the possible quotas found here: https://github.com/operate-first/apps/tree/master/cluster-scope/components/resourcequotas

Not sure how to handle custom quotas, can leave that manual for now.

**Comment by larsks** [comment]
If `-q` is not specified, does that mean "use a default quota (which one?)" or does that mean "do not apply a quota"?

> the -nl flag should give us the

Flags are single letters or start with a `--`. This is the way.

**Comment by HumairAK** [comment]
Hrmm good question, I'm leaning towards default is no quota, unless someone has a strong stance otherwise. 

> This is the way.

![image](https://user-images.githubusercontent.com/10904967/119149242-56ea2180-ba1b-11eb-9742-d90cac1eb068.png)
